spring:
  application:
    name: tmdb-service-search
server:
  port: 8081

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    api-key: <TOKEN-PERSONAL-TMDB>
  cache:
    ttl: 600 # Cache time-to-live in seconds

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
        recordExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
    instances:
      tmdbApiCircuitBreaker:
        baseConfig: default

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.tmdbservice: DEBUG
  file:
    name: logs/tmdb-service.log